In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Data/vine_table.csv")

In [3]:
df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
0,REAKC26P07MDN,5.0,0.0,0.0,N,Y
1,R3NU7OMZ4HQIEG,2.0,0.0,1.0,N,Y
2,R14QJW3XF8QO1P,5.0,0.0,0.0,N,Y
3,R2HB7AX0394ZGY,5.0,0.0,0.0,N,Y
4,RGKMPDQGSAHR3,5.0,0.0,0.0,N,Y
...,...,...,...,...,...,...
2643614,R40AVFLMGSX5Q,1.0,32.0,34.0,N,N
2643615,R13RP6H1OP0BFS,5.0,3.0,3.0,N,N
2643616,R34ITLN8LBTFZN,3.0,48.0,56.0,N,N
2643617,R30D2N6TX0OFS,3.0,7.0,7.0,N,Y
2643618,R2MAGOAOXPFMF1,2.0,17.0,20.0,N,Y

In [7]:
step1_filter_df=df.loc[df["total_votes"]>=20]
step1_filter_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase
128,R21KC552Y6HL8X,1.0,27.0,31.0,N,Y
161,RX9WC9FTIR1XR,5.0,25.0,25.0,N,Y
256,RGDCOU1KBHMNG,3.0,29.0,31.0,N,Y
267,RVTYWID2TPMMY,2.0,35.0,42.0,N,Y
719,R2CMPZ5VESGRLY,4.0,27.0,28.0,N,Y
...,...,...,...,...,...,...
2643586,RDDVO19Y8YH01,1.0,12.0,56.0,N,N
2643591,RU2X9GTDZ00IM,5.0,58.0,59.0,N,N
2643614,R40AVFLMGSX5Q,1.0,32.0,34.0,N,N
2643616,R34ITLN8LBTFZN,3.0,48.0,56.0,N,N
2643618,R2MAGOAOXPFMF1,2.0,17.0,20.0,N,Y

In [18]:
step1_filter_df["vote_ratio"]=round(step1_filter_df["helpful_votes"]/step1_filter_df["total_votes"]*100,2)

/var/folders/bv/vmvp5g1927n_rwgrdcs5g1dc0000gn/T/ipykernel_84902/1962039750.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  step1_filter_df["vote_ratio"]=round(step1_filter_df["helpful_votes"]/step1_filter_df["total_votes"]*100,2)

In [19]:
step1_filter_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,vote_ratio
128,R21KC552Y6HL8X,1.0,27.0,31.0,N,Y,87.10
161,RX9WC9FTIR1XR,5.0,25.0,25.0,N,Y,100.00
256,RGDCOU1KBHMNG,3.0,29.0,31.0,N,Y,93.55
267,RVTYWID2TPMMY,2.0,35.0,42.0,N,Y,83.33
719,R2CMPZ5VESGRLY,4.0,27.0,28.0,N,Y,96.43
...,...,...,...,...,...,...,...
2643586,RDDVO19Y8YH01,1.0,12.0,56.0,N,N,21.43
2643591,RU2X9GTDZ00IM,5.0,58.0,59.0,N,N,98.31
2643614,R40AVFLMGSX5Q,1.0,32.0,34.0,N,N,94.12
2643616,R34ITLN8LBTFZN,3.0,48.0,56.0,N,N,85.71
2643618,R2MAGOAOXPFMF1,2.0,17.0,20.0,N,Y,85.00

In [20]:
step2_filter_df=step1_filter_df.loc[step1_filter_df["vote_ratio"]>=50.00]
step2_filter_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,vote_ratio
128,R21KC552Y6HL8X,1.0,27.0,31.0,N,Y,87.10
161,RX9WC9FTIR1XR,5.0,25.0,25.0,N,Y,100.00
256,RGDCOU1KBHMNG,3.0,29.0,31.0,N,Y,93.55
267,RVTYWID2TPMMY,2.0,35.0,42.0,N,Y,83.33
719,R2CMPZ5VESGRLY,4.0,27.0,28.0,N,Y,96.43
...,...,...,...,...,...,...,...
2643577,R37NBT4U1EL04K,5.0,47.0,61.0,N,N,77.05
2643591,RU2X9GTDZ00IM,5.0,58.0,59.0,N,N,98.31
2643614,R40AVFLMGSX5Q,1.0,32.0,34.0,N,N,94.12
2643616,R34ITLN8LBTFZN,3.0,48.0,56.0,N,N,85.71
2643618,R2MAGOAOXPFMF1,2.0,17.0,20.0,N,Y,85.00

In [31]:
total_five_star_reviews_df=step2_filter_df.loc[step2_filter_df["star_rating"]==5.0]
total_five_star_reviews=len(total_five_star_reviews_df)
total_five_star_reviews

20677

In [35]:
paid_reviews_df=step2_filter_df.loc[step2_filter_df["vine"]=="Y"]
paid_reviews_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,vote_ratio
8547,R3A71VR1JZD8WF,2.0,27.0,30.0,Y,N,90.00
10246,R16OMUJIGI18JZ,5.0,72.0,72.0,Y,N,100.00
25168,R3TS8ZP2FHQ9XR,5.0,39.0,42.0,Y,N,92.86
46422,R2MHP919VZN7DI,5.0,29.0,30.0,Y,N,96.67
66446,RD2BCTVS59A5L,2.0,20.0,20.0,Y,N,100.00
...,...,...,...,...,...,...,...
2596353,RV5OQXGCYHSC6,5.0,24.0,28.0,Y,N,85.71
2596519,R2XLAQL0E2UPWQ,4.0,33.0,34.0,Y,N,97.06
2597336,R2UJFVH97OJORD,3.0,106.0,117.0,Y,N,90.60
2597830,RJXG84I331N9T,3.0,146.0,154.0,Y,N,94.81
2598196,RNGRV0353CDWX,4.0,109.0,115.0,Y,N,94.78

In [41]:
paid_five_star_reviews_df=paid_reviews_df.loc[paid_reviews_df["star_rating"]==5.0]
paid_five_star_reviews=len(paid_five_star_reviews_df)
paid_five_star_reviews

65

In [43]:
paid_reviews_ratio=round(paid_five_star_reviews/len(paid_reviews_df)*100,2)
paid_reviews_ratio

38.24

In [22]:
unpaid_reviews_df=step2_filter_df.loc[step2_filter_df["vine"]=="N"]
unpaid_reviews_df

,review_id,star_rating,helpful_votes,total_votes,vine,verified_purchase,vote_ratio
128,R21KC552Y6HL8X,1.0,27.0,31.0,N,Y,87.10
161,RX9WC9FTIR1XR,5.0,25.0,25.0,N,Y,100.00
256,RGDCOU1KBHMNG,3.0,29.0,31.0,N,Y,93.55
267,RVTYWID2TPMMY,2.0,35.0,42.0,N,Y,83.33
719,R2CMPZ5VESGRLY,4.0,27.0,28.0,N,Y,96.43
...,...,...,...,...,...,...,...
2643577,R37NBT4U1EL04K,5.0,47.0,61.0,N,N,77.05
2643591,RU2X9GTDZ00IM,5.0,58.0,59.0,N,N,98.31
2643614,R40AVFLMGSX5Q,1.0,32.0,34.0,N,N,94.12
2643616,R34ITLN8LBTFZN,3.0,48.0,56.0,N,N,85.71
2643618,R2MAGOAOXPFMF1,2.0,17.0,20.0,N,Y,85.00

In [44]:
unpaid_five_star_reviews_df=unpaid_reviews_df.loc[unpaid_reviews_df["star_rating"]==5.0]
unpaid_five_star_reviews=len(unpaid_five_star_reviews_df)
unpaid_five_star_reviews

20612

In [45]:
unpaid_reviews_ratio=round(unpaid_five_star_reviews/len(unpaid_reviews_df)*100,2)
unpaid_reviews_ratio

54.47